### ISSUE TITLE
Questions Regarding the Aging Cell Discrimination Threshold and Normalization Method

### ISSUE THREAD

**Issue by merlinTFG** [JackieHanLab/SenCID#1]
Hello,

First of all, I would like to express my gratitude for developing this outstanding method for discriminating aging cells. It has been very useful in my research. However, I have encountered a couple of issues that I hope you could clarify:

Threshold for Aging Cell Discrimination:
I noticed that a threshold of 0.5 is used to distinguish aging cells. In practice, I found that the aging scores vary significantly depending on the sequencing technique used. For the same cell population, most of the aging scores are above 0.5 in single-cell sequencing samples, while scores from the same population post-flow cytometry and bulk sequencing are mostly below 0.5, despite originating from the same samples. Could you elaborate on why 0.5 was chosen as the threshold and how it might be adjusted for different sequencing technologies?

Normalization Using Logistic Regression Model:
According to your paper, I calculated the aging scores using SID6, and the scores for Group A were significantly higher than those for Group B. However, when looking directly at SID6 scores (both raw and simply normalized), Group A's scores are significantly lower than those of Group B. Could you explain the rationale behind using a logistic regression model for normalization in this context?

I am eager to better understand these aspects to effectively utilize your algorithm in my research. Thank you for your time and assistance.

**Comment by SherryMiyano** [comment]
Hello, thank you for reaching out and for your support of SenCID! 
For the threshold settings, you may refer to our paper (Tao, et al. https://doi.org/10.1016/j.cmet.2024.03.009). On Figure S6D-H and the related text, we discussed about the chosen of the threshold. Currently, it's not recommended to compare the bulk and single cell score results directly, as they represent different perspectives – one being an aggregate statistic and the other focusing on individual cell predictions. But if there's a need for pairing, I personally would suggest optimizing the threshold where the ratio of senescent single cells to be consistent with the bulk scores. 
For the other query, I'm quite confused of the two terms you refer to: "aging scores using SID6" and "directly at SID6 scores". Nevertheless, you may see in Figure S2A-B and the associated text, we elucidate the process of training our logistic regression model using features selected from RFE-SVM with the aim of normalizing the SID scores to all fall within a range of 0 to 1, enabling interpretation as probabilities of senescence for individual cells or samples. We also incorporate the decision function from SVM as a part of the output. This ensures that our tool accommodates users with varying preferences, whether they emphasize senescence extent comparisons between treatments or seek to focus primarily on the identification of senescent cells.
Hope I've taken your questions correctly.

**Comment by merlinTFG** [comment]
感谢您的及时回复。
    第二个问题我可能没有阐释清楚。在实际应用过程中，我发现我的目标细胞亚群适合使用rec_SID6。而使用pred_dict函数获得SID_Score后，A组SID_Score显著高于B组，但如果不用pred_dict而直接比较rec_SID6评分，则A组rec_SID6评分显著低于B组，这是我感到困惑的地方。这种时候您更推荐选择哪种比较方式？
    另外昨天我下载了“Senescence‐associated β‐galactosidase reveals the abundance of senescent CD8+ T cells in aging humans”GSE169009数据集，提取其中六个样本的raw counts，并按照您提供的SenCID_tutorial.ipynb进行重复，但是获得的SID_Score差异不如您文章中supplementary里展示的SIDscore那么大，您还进行了其他特殊的处理步骤吗？

**Comment by SherryMiyano** [comment]
> ```
> 感谢您的及时回复。
> 第二个问题我可能没有阐释清楚。在实际应用过程中，我发现我的目标细胞亚群适合使用rec_SID6。而使用pred_dict函数获得SID_Score后，A组SID_Score显著高于B组，但如果不用pred_dict而直接比较rec_SID6评分，则A组rec_SID6评分显著低于B组，这是我感到困惑的地方。这种时候您更推荐选择哪种比较方式？
> 另外昨天我下载了“Senescence‐associated β‐galactosidase reveals the abundance of senescent CD8+ T cells in aging humans”GSE169009数据集，提取其中六个样本的raw counts，并按照您提供的SenCID_tutorial.ipynb进行重复，但是获得的SID_Score差异不如您文章中supplementary里展示的SIDscore那么大，您还进行了其他特殊的处理步骤吗？
> ```

感谢您的清晰描述~

这边解释一下几个数值。rec_SID6的作用只是判断样品是否属于SID6，如果rec_SID6的数值比其他rec_SID都高，代表该样品是属于SID6的，但rec_SID6本身不含有评估衰老的性质。针对您这种情况，SID6模型的SID_Score才是比较衰老的标准。所以应该用A组SID_Score显著高于B组这个结果。

后面的问题，您可以看一下denoising这个参数有没有设置为F（demo使用的是单细胞数据，其中denoising被设置为T，因为需要填补其中的dropout。但GSE169009属于bulk RNA-seq，这一项需要关掉）。

**Comment by merlinTFG** [comment]
谢谢，非常详细清楚了
