### ISSUE TITLE
Can we apply SenCID to 10X Genomics sc-RNA seq?

### ISSUE THREAD

**Issue by seasonzhao** [JackieHanLab/SenCID#14]
_Our analysis re- veals that the BTD-trained SenCID is applicable to both Dropseq- (Figures 2A, 2C, 2D, and 2F) and Smart-seq- (Figure 2B) generated single-cell data._

Is there any difference between 10X, Dropseq and Smart-seq?
Can we apply SenCID to 10X Genomics sc-RNA seq?

**Comment by LucasLiu20200131** [comment]
I have the same question about applying SenCID to 10X Genomics sc-RNA seq, looking forward to the reply.

**Comment by SherryMiyano** [comment]
Hello, thanks for the support for SenCID! 

In the referenced description, I've included 10X Genomics into the generalized term of 'Dropseq' (in fact, Figure 2A, 2D and 2F are all from 10X), so feel free to perform SenCID on 10X Genomics. There's no difference in parameter settings between 10X, Dropseq or Smart-seq as input.

**Comment by seasonzhao** [comment]
Thank you so much! I will try it
