### ISSUE TITLE
Differences after dividing one dataset into files.

### ISSUE THREAD

**Issue by Xxhongs** [JackieHanLab/SenCID#6]
Hello,

SenCID is an excellent tool for identifying senescent cells. 

However, I observed that, after dividing the same dataset into two files and rerun the SenCID program, there were some differences between the two results, including the RecSID and Binarization of senescent cells.

In practical applications, does consolidating all cell expression matrices into a single file improve the accuracy of analysis results? This is crucial to consider, especially when dealing with large numbers of cells, as consolidating them into one file can be challenging.

**Comment by SherryMiyano** [comment]
Hello, 

The difference you pointed out come from the [DCA](https://github.com/theislab/dca) imputation for single cell data. You may check their manuscript for the principle of this dependency. Generally, there would not be large difference if you split the data into two, as long as each subdata contain enough single cells for the autoencoder training. One thing to be noted is to always turn off DCA imputation (by setting parameter denoising = False) when you perform SenCID in bulk RNA-seq data.

**Comment by Xxhongs** [comment]
I'm really grateful for your help.
Thank you ever so much!
